dist: trusty
group: deprecated-2017Q4
python:
    - 2.7
services:
    - postgresql
    - redis-server
env:
    - CKANVERSION=master
    - CKANVERSION=2.8.2
install:
    - bash bin/travis-build.bash
    - pip install coveralls
script: sh bin/travis-run.sh
after_success:
    - coveralls
