language: python
sudo: required
python:
    - "2.7"
services:
    - postgresql
    - redis-server
env:
    - CKAN_VERSION=master
    - CKAN_VERSION=dev-v2.8
install:
    - bash bin/travis-build.bash
    - pip install coveralls
script: sh bin/travis-run.sh
after_success:
    - coveralls
