name: Tests
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 2.7, 3.9 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: |
          flake8 . --count --max-line-length=127 --show-source --statistics
  test:
    name: CKAN
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ckan-container-version: "2.9-py2"
            ckan-postgres-version: "2.9"
            ckan-solr-version: "2.9-solr8"
          - ckan-container-version: "2.9"
            ckan-postgres-version: "2.9"
            ckan-solr-version: "2.9-solr8"
          - ckan-container-version: "2.10"
            ckan-postgres-version: "2.10"
            ckan-solr-version: "2.10"

    container:
      image: openknowledge/ckan-dev:${{ matrix.ckan-container-version }}
    services:
      solr:
        image: ckan/ckan-solr:${{ matrix.ckan-solr-version }}
      postgres:
        image: ckan/ckan-postgres-dev:${{ matrix.ckan-postgres-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
          image: redis:3
    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        pip install -e .
        # Replace default path to CKAN core config file with the one on the container
        sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini
    - name: Setup extension
      run: |
        ckan -c test.ini db init
    - name: Run tests
      run: pytest --ckan-ini=test.ini --cov=ckanext.emailasusername --disable-warnings ckanext/emailasusername/tests
